//
// Created by rowlke01 on 3/22/19.
//

#ifndef HPCCSYSTEMS_PLATFORM_ENVIRONMENTTYPES_HPP
#define HPCCSYSTEMS_PLATFORM_ENVIRONMENTTYPES_HPP

enum EnvironmentType
{
    UNDEFINED,
    XML
};

#endif //HPCCSYSTEMS_PLATFORM_ENVIRONMENTTYPES_HPP
